#!/usr/bin/env bash
set -e

MINER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${CUSTOM_CONFIG_FILENAME:-${MINER_DIR}/amdbtx.yaml}"
ARGS_FILE="${CONFIG_FILE}.args"
DEFAULT_POOL="btx-sg.lproute.com:8660"

finish_error() {
    echo "$*" >&2
    return 1 2>/dev/null || exit 1
}

replace_hive_tokens() {
    local value="$1"
    value="${value//%WAL%/${WAL:-}}"
    value="${value//%EWAL%/${EWAL:-}}"
    value="${value//%DWAL%/${DWAL:-}}"
    value="${value//%ZWAL%/${ZWAL:-}}"
    value="${value//%EMAIL%/${EMAIL:-}}"
    value="${value//%WORKER_NAME%/${WORKER_NAME:-}}"
    value="${value//%WORKER%/${WORKER_NAME:-}}"
    printf '%s' "$value"
}

trim() {
    local value="$1"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf '%s' "$value"
}

yaml_quote() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '"%s"' "$value"
}

pool_host=""
pool_port=""
pool_tls="false"

parse_pool() {
    local raw first endpoint scheme
    raw="$(trim "$(replace_hive_tokens "${CUSTOM_URL:-$DEFAULT_POOL}")")"
    [[ -n "$raw" ]] || raw="$DEFAULT_POOL"

    first="${raw%%,*}"
    scheme=""
    if [[ "$first" == *"://"* ]]; then
        scheme="${first%%://*}"
        endpoint="${first#*://}"
    else
        endpoint="$first"
    fi

    case "$scheme" in
        *ssl*|*tls*) pool_tls="true" ;;
        *) pool_tls="false" ;;
    esac

    endpoint="${endpoint%%/*}"
    endpoint="${endpoint##*@}"

    if [[ "$endpoint" == *":"* ]]; then
        pool_host="${endpoint%:*}"
        pool_port="${endpoint##*:}"
    else
        pool_host="$endpoint"
        pool_port="8660"
    fi

    [[ -n "$pool_host" ]] || pool_host="${DEFAULT_POOL%:*}"
    [[ "$pool_port" =~ ^[0-9]+$ ]] || pool_port="${DEFAULT_POOL##*:}"
}

extract_wallet_and_worker() {
    local template value
    template="${CUSTOM_TEMPLATE:-${WAL:-}}"
    value="$(trim "$(replace_hive_tokens "$template")")"

    PAYOUT_ADDRESS="${value%%.*}"
    if [[ "$value" == *.* ]]; then
        WORKER="${value#*.}"
    else
        WORKER="${WORKER_NAME:-default}"
    fi

    PAYOUT_ADDRESS="$(trim "$PAYOUT_ADDRESS")"
    WORKER="$(trim "$WORKER")"
    [[ -n "$WORKER" ]] || WORKER="default"
}

append_extra_config() {
    local extra
    extra="$(trim "$(replace_hive_tokens "${CUSTOM_USER_CONFIG:-}")")"
    : > "$ARGS_FILE"
    [[ -n "$extra" ]] || return 0

    if grep -q ':' <<<"$extra"; then
        {
            echo
            echo "# HiveOS Extra config arguments"
            printf '%s\n' "$extra"
        } >> "$CONFIG_FILE"
    else
        printf '%s\n' "$extra" > "$ARGS_FILE"
    fi
}

parse_pool
extract_wallet_and_worker
[[ -n "$PAYOUT_ADDRESS" ]] || finish_error "AMDBTX: wallet is empty. Set Wallet and worker template to %WAL%.%WORKER_NAME% or specify a BTX address."

mkdir -p "$(dirname "$CONFIG_FILE")"

{
    echo "# AMDBTX HiveOS config - generated by h-config.sh"
    echo 'mining_mode: "pool"'
    echo
    printf 'pool_host: %s\n' "$(yaml_quote "$pool_host")"
    printf 'pool_port: %s\n' "$pool_port"
    printf 'pool_tls: %s\n' "$pool_tls"
    echo 'pool_protocol: "luckypool"'
    echo
    printf 'payout_address: %s\n' "$(yaml_quote "$PAYOUT_ADDRESS")"
    printf 'worker_name: %s\n' "$(yaml_quote "$WORKER")"
    echo
    printf 'gbt_solve_path: %s\n' "$(yaml_quote "${HOME:-/root}/.amdbtx-miner/bin/btx-gbt-solve-hip")"
    echo
    echo 'solver_backend: "rocm"'
    echo 'solver_threads: 16'
    echo 'solver_prepare_workers: 16'
    echo 'solver_batch_size: 4194304'
    echo 'solver_prefetch_depth: 8'
    echo 'solver_pipeline_async: 1'
    echo 'gpu_inputs: 1'
    echo 'gpu_devices: "all"'
    echo
    echo 'nonces_per_slice: 20000000'
    echo 'solver_max_seconds_per_slice: 5.0'
    echo 'pool_max_shares_per_slice: 0'
    echo
    echo 'reconnect_initial_s: 1.0'
    echo 'reconnect_max_s: 60.0'
    echo 'log_level: "INFO"'
} > "$CONFIG_FILE"

append_extra_config
