# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for amdbtx-miner (Windows).
# Generated by build_and_package_windows.ps1 — paths are repo-relative and resolve
# from this file's location so it works on any machine that clones the repo at the
# same drive.
import os
from PyInstaller.utils.hooks import collect_submodules

_spec_dir = os.path.dirname(os.path.abspath(SPEC))
def _r(path):
    return os.path.normpath(os.path.join(_spec_dir, path))

SOLVER_BIN = _r(os.environ.get('AMDBTX_SOLVER_BIN', r'..\\solver\\build-win\\btx-gbt-solve-hip'))
RUNTIME_DIR = _r(os.environ.get('AMDBTX_RUNTIME_DIR', r'..\\solver\\build-win\\runtime'))
ENTRY = _r(os.environ.get('AMDBTX_ENTRY', r'..\\src\\run_miner.py'))

if not os.path.exists(SOLVER_BIN):
    raise SystemExit(f'solver binary not found: {SOLVER_BIN} — run build_and_package_windows.ps1 first')
if not os.path.isdir(RUNTIME_DIR):
    raise SystemExit(f'runtime dir not found: {RUNTIME_DIR} — run build_and_package_windows.ps1 first')

hiddenimports = ['yaml']
hiddenimports += collect_submodules('amdbtx_miner')

a = Analysis(
    [ENTRY],
    pathex=[],
    binaries=[],
    datas=[(SOLVER_BIN, '.'), (RUNTIME_DIR, 'runtime')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='amdbtx-miner',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
